version: '3.7'

services:

  bot:
    &bot
    container_name: lockbot
    build: .
    environment:
      - SLACK_API_TOKEN
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    entrypoint: dockerize --wait tcp://redis:6379
    command: slack-machine

  redis:
    image: redis:3.2
    ports:
      - "6379"
